// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Tag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Color     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Task struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	Date        sql.NullTime
	TimeStart   sql.NullTime
	TimeEnd     sql.NullTime
	IsCompleted bool
	IsFavourite bool
	DeletedAt   sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TaskTag struct {
	TaskID uuid.UUID
	TagID  uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserProfile struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FullName  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
