// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserProfile struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FullName  string
	AvatarUrl sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
