// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO user_profiles (user_id, full_name, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, user_id, full_name, avatar_url, created_at, updated_at
`

type CreateProfileParams struct {
	UserID    uuid.UUID
	FullName  string
	AvatarUrl sql.NullString
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.UserID, arg.FullName, arg.AvatarUrl)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, full_name, avatar_url, created_at, updated_at FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE user_profiles
SET
    full_name  = COALESCE($1, full_name),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE user_id = $3
RETURNING id, user_id, full_name, avatar_url, created_at, updated_at
`

type UpdateProfileParams struct {
	FullName  sql.NullString
	AvatarUrl sql.NullString
	UserID    uuid.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile, arg.FullName, arg.AvatarUrl, arg.UserID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
