// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTagToTask = `-- name: AddTagToTask :exec
INSERT INTO task_tags (task_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToTaskParams struct {
	TaskID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) AddTagToTask(ctx context.Context, arg AddTagToTaskParams) error {
	_, err := q.db.ExecContext(ctx, addTagToTask, arg.TaskID, arg.TagID)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, name, description, date, time_start, time_end)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, date, time_start, time_end, is_completed, is_favourite, deleted_at, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	Date        sql.NullTime
	TimeStart   sql.NullTime
	TimeEnd     sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.IsCompleted,
		&i.IsFavourite,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByTaskID = `-- name: GetTagsByTaskID :many
SELECT t.id, t.user_id, t.name, t.color, t.created_at, t.updated_at FROM tags t
JOIN task_tags tt ON tt.tag_id = t.id
WHERE tt.task_id = $1
`

func (q *Queries) GetTagsByTaskID(ctx context.Context, taskID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, name, description, date, time_start, time_end, is_completed, is_favourite, deleted_at, created_at, updated_at FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.IsCompleted,
		&i.IsFavourite,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeTagFromTask = `-- name: RemoveTagFromTask :exec
DELETE FROM task_tags WHERE task_id = $1 AND tag_id = $2
`

type RemoveTagFromTaskParams struct {
	TaskID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) RemoveTagFromTask(ctx context.Context, arg RemoveTagFromTaskParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTask, arg.TaskID, arg.TagID)
	return err
}

const restoreTask = `-- name: RestoreTask :exec
UPDATE tasks SET deleted_at = NULL
WHERE id = $1 AND user_id = $2
`

type RestoreTaskParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RestoreTask(ctx context.Context, arg RestoreTaskParams) error {
	_, err := q.db.ExecContext(ctx, restoreTask, arg.ID, arg.UserID)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type SoftDeleteTaskParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, arg.ID, arg.UserID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name = $3, description = $4, date = $5, time_start = $6, time_end = $7, is_completed = $8, is_favourite = $9, updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, description, date, time_start, time_end, is_completed, is_favourite, deleted_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	Date        sql.NullTime
	TimeStart   sql.NullTime
	TimeEnd     sql.NullTime
	IsCompleted bool
	IsFavourite bool
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.TimeStart,
		arg.TimeEnd,
		arg.IsCompleted,
		arg.IsFavourite,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.TimeStart,
		&i.TimeEnd,
		&i.IsCompleted,
		&i.IsFavourite,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
